/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unab.proyecto.view;

/**
 *
 * @author jank
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbSistema = new javax.swing.JComboBox<>();
        cbOperacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdato1 = new javax.swing.JTextField();
        dato1 = new javax.swing.JLabel();
        dato2 = new javax.swing.JLabel();
        signo = new javax.swing.JLabel();
        txtdato2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbSistema.setBackground(new java.awt.Color(51, 0, 51));
        cbSistema.setForeground(new java.awt.Color(255, 255, 255));
        cbSistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, -1));

        cbOperacion.setBackground(new java.awt.Color(51, 0, 51));
        cbOperacion.setForeground(new java.awt.Color(255, 255, 255));
        cbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOperacionItemStateChanged(evt);
            }
        });
        jPanel1.add(cbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Operacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        txtdato1.setBackground(new java.awt.Color(51, 0, 51));
        txtdato1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, -1));

        dato1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 20));

        dato2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 20));

        signo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 20, 30));

        txtdato2.setBackground(new java.awt.Color(51, 0, 51));
        txtdato2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 80, -1));

        txtResultado.setBackground(new java.awt.Color(51, 0, 51));
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 90, -1));

        btnCalcular.setBackground(new java.awt.Color(0, 0, 51));
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 490, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CALCULADORA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 0, 51));
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOperacionItemStateChanged
        // TODO add your handling code here:
        String datos =(String)cbOperacion.getSelectedItem();
        if (datos=="Seleccionar"){
            signo.setText("");
            dato1.setText("");
            dato2.setText("");
        }
        if (datos=="Suma"){
            signo.setText("+");
            dato1.setText("Sumandos");
            dato2.setText("Sumandos");
        }
        if (datos=="Resta"){
            signo.setText("-");
            dato1.setText("Minuendo");
            dato2.setText("Sustraendo");
        }
        if (datos=="Multiplicación"){
            signo.setText("*");
            dato1.setText("Multiplicando");
            dato2.setText("Multiplicador");
        }
        if (datos=="División"){
            signo.setText("/");
            dato1.setText("Dividendo");
            dato2.setText("Divisor");
        }
        if (datos=="Radicación"){
            signo.setText("√");
            dato1.setText("Indice");
            dato2.setText("Radicando");
        }
        if (datos=="Potenciación"){
            signo.setText("^");
            dato1.setText("Base");
            dato2.setText("Exponente");
        }
    }//GEN-LAST:event_cbOperacionItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cbOperacion;
    public javax.swing.JComboBox<String> cbSistema;
    public javax.swing.JLabel dato1;
    public javax.swing.JLabel dato2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel signo;
    public javax.swing.JTextField txtResultado;
    public javax.swing.JTextField txtdato1;
    public javax.swing.JTextField txtdato2;
    // End of variables declaration//GEN-END:variables
}
